apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: artificial-or-natural-intelligence
data:
  PG_HOST: postgres
  PG_PORT: "5432"
  API_PORT: "80"

  BASE_URL: "http://34.27.222.49"
  ANGULAR_URL: "http://34.49.229.24"

  DOCS_ENDPOINT: "/docs"
  CONTENT_ENDPOINT: "/content"
  CONTENT_DIR: "/app/content"

  FRONTEND_LAST_LEVEL: "5"
  FRONTEND_MAX_QUESTIONS_PER_LEVEL: "2"
  FRONTEND_HINTS_ENABLED: "true"