apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: google-secret-manager
  namespace: artificial-or-natural-intelligence
spec:
  provider:
    gcpsm:
      projectID: project-630566f1-fd55-4ba6-b5e
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: artificial-or-natural-intelligence
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: artificial-or-natural-intelligence-app-secret